import os
import asyncio
import logging
import tempfile
import yt_dlp
import re
import random
import time
import requests
from pyrogram import Client, filters
from pyrogram.errors import BadRequest, BadMsgNotification
from pyrogram.types import InputMediaPhoto, InputMediaVideo
import instaloader
import aiohttp
import shutil
from concurrent.futures import ThreadPoolExecutor

API_ID = 26670278
API_HASH = "e3d77390fd9c22d98bb6bddca86fef1a"
BOT_TOKEN = "6788128988:AAEMmCSafiiEqtS5UWQQxfo--W0On7B6Q08"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ------------------------- ГЛОБАЛЬНЫЕ ПЕРЕМЕННЫЕ -------------------------
user_processing = {}
processed_messages = set()

# ------------------------- ОПТИМИЗИРОВАННЫЙ SafeClient -------------------------
class SafeClient(Client):
    async def send(self, *args, **kwargs):
        for attempt in range(3):
            try:
                return await super().send(*args, **kwargs)
            except BadMsgNotification as e:
                if e.error_code == 16:
                    logger.warning(f"[WARN] BadMsgNotification [16], исправляем msg_id, попытка {attempt + 1}/3")
                    self.session.msg_id_offset = int(time.time() * 2**32)
                    await asyncio.sleep(1)
                else:
                    raise
        raise RuntimeError("Не удалось синхронизировать msg_id с Telegram")

# ------------------------- ОПТИМИЗИРОВАННЫЙ КЛИЕНТ -------------------------
app = SafeClient(
    "video_bot_new_session_2024",
    api_id=API_ID,
    api_hash=API_HASH,
    bot_token=BOT_TOKEN,
    sleep_threshold=30,
    workers=100,
)

# ------------------------- УЛУЧШЕННЫЙ Instagram Downloader -------------------------
class InstagramDownloader:
    def __init__(self):
        # ПРОВЕРЯЕМ И ФИКСИМ COOKIES ПРИ ИНИЦИАЛИЗАЦИИ
        self._setup_cookies()
        
        # ОПТИМИЗИРОВАННЫЕ НАСТРОЙКИ yt-dlp
        self.fast_ydl_opts = {
            'outtmpl': 'downloads/%(id)s.%(ext)s',
            'format': 'best[height<=720]',
            'cookiefile': 'cookies.txt',
            'quiet': True,
            'no_warnings': True,
            'extract_flat': False,
            'noplaylist': True,
            
            # ⚡ ОПТИМИЗАЦИИ СКОРОСТИ И СТАБИЛЬНОСТИ
            'socket_timeout': 20,
            'extractretry': 2,
            'retries': 3,
            'fragment_retries': 3,
            'skip_unavailable_fragments': True,
            'keep_fragments': False,
            'concurrent_fragment_downloads': 4,
            
            # УЛУЧШЕННЫЕ ЗАГОЛОВКИ
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept': '*/*',
                'Accept-Language': 'en-US,en;q=0.9',
                'Accept-Encoding': 'gzip, deflate, br',
                'Referer': 'https://www.instagram.com/',
                'Origin': 'https://www.instagram.com',
            }
        }
        
        # Настройки для instaloader
        self.instaloader_session = "instagram_session"
        self.thread_pool = ThreadPoolExecutor(max_workers=3)

    def _setup_cookies(self):
        """Проверяем и фиксим cookies файл"""
        if not os.path.exists("cookies.txt"):
            logger.error("❌ Файл cookies.txt не найден!")
            # Создаем базовый файл cookies
            self._create_default_cookies()
            return False
        
        # Проверяем формат cookies
        with open("cookies.txt", "r", encoding="utf-8") as f:
            content = f.read()
            
        # Проверяем Netscape формат
        if not content.startswith("# Netscape HTTP Cookie File"):
            logger.warning("⚠️ Файл cookies не в Netscape формате, пытаемся исправить...")
            self._fix_cookies_format(content)
        
        logger.info("✅ Файл cookies.txt проверен")
        return True

    def _create_default_cookies(self):
        """Создает базовый файл cookies"""
        default_cookies = """# Netscape HTTP Cookie File
# This file is generated by Instagram Downloader
# To update cookies, export from your browser while logged into Instagram

.instagram.com	TRUE	/	TRUE	0	sessionid	YOUR_SESSION_ID_HERE
.instagram.com	TRUE	/	TRUE	0	csrftoken	YOUR_CSRF_TOKEN_HERE
.instagram.com	TRUE	/	TRUE	0	ds_user_id	YOUR_USER_ID_HERE
"""
        with open("cookies.txt", "w", encoding="utf-8") as f:
            f.write(default_cookies)
        logger.warning("📝 Создан шаблон cookies.txt - заполните своими данными!")

    def _fix_cookies_format(self, content):
        """Исправляет формат cookies файла"""
        try:
            lines = content.strip().split('\n')
            fixed_lines = ["# Netscape HTTP Cookie File", "# Fixed by Instagram Downloader"]
            
            for line in lines:
                if line.strip() and not line.startswith('#'):
                    parts = line.split('\t')
                    if len(parts) >= 7:
                        fixed_lines.append(line)
                    else:
                        # Пытаемся исправить неправильный формат
                        if '=' in line:
                            name_value = line.split('=', 1)
                            if len(name_value) == 2:
                                fixed_lines.append(f".instagram.com\tTRUE\t/\tTRUE\t0\t{name_value[0]}\t{name_value[1]}")
            
            with open("cookies.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(fixed_lines))
            logger.info("✅ Формат cookies исправлен")
            
        except Exception as e:
            logger.error(f"❌ Ошибка исправления cookies: {e}")

    async def download_instagram_content(self, url: str, out_path: str):
        """УЛУЧШЕННАЯ функция для скачивания с лучшей обработкой ошибок"""
        try:
            loop = asyncio.get_event_loop()
            content_type = self._determine_content_type(url)
            logger.info(f"🔍 Определен тип контента: {content_type}")
            
            # ПЕРВЫЙ СПОСОБ: yt-dlp с cookies
            try:
                result = await loop.run_in_executor(
                    self.thread_pool,
                    self._download_with_ytdlp_enhanced,
                    url, out_path, content_type
                )
                if result and result.get('files'):
                    logger.info("✅ Успешно скачано через yt-dlp с cookies")
                    return result
            except Exception as e:
                logger.warning(f"📌 yt-dlp с cookies не сработал: {e}")

            # ВТОРОЙ СПОСОБ: instaloader с сессией
            try:
                result = await self._download_with_instaloader_enhanced(url, out_path)
                if result and result.get('files'):
                    logger.info("✅ Успешно скачано через instaloader")
                    return result
            except Exception as e:
                logger.warning(f"📌 Instaloader не сработал: {e}")

            # ТРЕТИЙ СПОСОБ: yt-dlp без cookies (fallback)
            try:
                result = await loop.run_in_executor(
                    self.thread_pool,
                    self._download_with_ytdlp_fallback,
                    url, out_path, content_type
                )
                if result and result.get('files'):
                    logger.info("✅ Успешно скачано через yt-dlp fallback")
                    return result
            except Exception as e:
                logger.warning(f"📌 yt-dlp fallback не сработал: {e}")

            raise Exception("Все методы скачивания не сработали")

        except Exception as e:
            logger.error(f"❌ Все методы скачивания провалились: {e}")
            raise

    def _download_with_ytdlp_enhanced(self, url: str, out_path: str, content_type: str):
        """УЛУЧШЕННЫЙ метод yt-dlp с проверкой cookies"""
        ydl_opts = self.fast_ydl_opts.copy()
        ydl_opts['outtmpl'] = os.path.join(out_path, '%(id)s.%(ext)s')
        
        # Добавляем проверку cookies
        if os.path.exists("cookies.txt"):
            ydl_opts['cookiefile'] = "cookies.txt"
        
        # Настройки для разных типов контента
        if content_type == 'video':
            ydl_opts['format'] = 'best[ext=mp4]/best'
        elif content_type == 'photo':
            ydl_opts['format'] = 'best[ext=jpg]/best[ext=png]/best'
        
        # Добавляем обходные пути
        ydl_opts['extractor_args'] = {
            'instagram': {
                'skip_auth': True,
                'extract_comments': False,
                'post_filter': 'none'
            }
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            
            result = {
                'type': 'unknown',
                'files': [],
                'title': info.get('title', 'instagram_content'),
                'webpage_url': info.get('webpage_url', url)
            }
            
            # Сбор файлов
            if info.get('requested_downloads'):
                for download in info['requested_downloads']:
                    file_path = download['filepath']
                    if os.path.exists(file_path) and self._is_media_file_fast(file_path):
                        result['files'].append(file_path)
            
            # Поиск в директории
            if not result['files']:
                for file in os.listdir(out_path):
                    file_path = os.path.join(out_path, file)
                    if self._is_media_file_fast(file_path):
                        result['files'].append(file_path)
            
            # Определение типа
            if info.get('_type') == 'playlist' or len(result['files']) > 1:
                result['type'] = 'carousel'
            else:
                if result['files']:
                    ext = result['files'][0].split('.')[-1].lower()
                    if ext in ['jpg', 'png', 'jpeg']:
                        result['type'] = 'photo'
                    elif ext in ['mp4', 'mov', 'avi']:
                        result['type'] = 'video'
            
            return result

    def _download_with_ytdlp_fallback(self, url: str, out_path: str, content_type: str):
        """Fallback метод без cookies для публичного контента"""
        ydl_opts = {
            'outtmpl': os.path.join(out_path, '%(id)s.%(ext)s'),
            'format': 'best[height<=480]',  # Более низкое качество для надежности
            'quiet': True,
            'no_warnings': False,
            'socket_timeout': 30,
            'extractretry': 1,
            'retries': 1,
            'fragment_retries': 1,
            'skip_unavailable_fragments': True,
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Accept': '*/*',
            }
        }
        
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            
            result = {
                'type': 'unknown',
                'files': [],
                'title': info.get('title', 'instagram_content'),
                'webpage_url': info.get('webpage_url', url)
            }
            
            for file in os.listdir(out_path):
                file_path = os.path.join(out_path, file)
                if self._is_media_file_fast(file_path):
                    result['files'].append(file_path)
            
            return result

    async def _download_with_instaloader_enhanced(self, url: str, out_path: str):
        """УЛУЧШЕННЫЙ метод instaloader с сессией"""
        try:
            L = instaloader.Instaloader(
                dirname_pattern=out_path,
                filename_pattern='{shortcode}',
                download_pictures=True,
                download_videos=True,
                download_geotags=False,
                download_comments=False,
                save_metadata=False,
                compress_json=False,
                request_timeout=30
            )
            
            # Пытаемся загрузить сессию
            try:
                if os.path.exists(f"{self.instaloader_session}.session"):
                    L.load_session_from_file(username=None, filename=self.instaloader_session)
                    logger.info("✅ Сессия instaloader загружена")
            except Exception as e:
                logger.warning(f"⚠️ Не удалось загрузить сессию instaloader: {e}")

            shortcode = self._extract_shortcode(url)
            if not shortcode:
                raise Exception("Не удалось извлечь shortcode из URL")
            
            post = instaloader.Post.from_shortcode(L.context, shortcode)
            L.download_post(post, target=out_path)
            
            downloaded_files = []
            for file in os.listdir(out_path):
                file_path = os.path.join(out_path, file)
                if self._is_media_file_fast(file_path):
                    downloaded_files.append(file_path)
            
            result = {
                'type': 'carousel' if post.mediacount > 1 else 'photo',
                'files': downloaded_files,
                'title': f"instagram_{shortcode}",
                'webpage_url': url
            }
            
            if downloaded_files:
                ext = downloaded_files[0].split('.')[-1].lower()
                if ext in ['mp4', 'mov', 'avi']:
                    result['type'] = 'video'
                    
            return result
            
        except Exception as e:
            raise Exception(f"Instaloader ошибка: {str(e)}")

    def _determine_content_type(self, url: str) -> str:
        """Быстрое определение типа контента"""
        if '/reel/' in url or '/reels/' in url or '/tv/' in url:
            return 'video'
        elif '/p/' in url:
            return 'post'
        elif '/stories/' in url:
            return 'story'
        else:
            return 'auto'

    def _is_media_file_fast(self, file_path: str) -> bool:
        """БЫСТРАЯ проверка медиафайла"""
        media_extensions = {'.jpg', '.jpeg', '.png', '.mp4', '.mov', '.avi', '.webm'}
        file_ext = os.path.splitext(file_path)[1].lower()
        return file_ext in media_extensions and os.path.isfile(file_path)

    def _extract_shortcode(self, url: str):
        patterns = [
            r'instagram\.com/p/([^/?]+)',
            r'instagram\.com/reel/([^/?]+)',
            r'instagram\.com/stories/[^/]+/([^/?]+)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, url)
            if match:
                return match.group(1)
        return None

# ------------------------- ОПТИМИЗИРОВАННЫЕ ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ -------------------------
def extract_first_url(text: str) -> str:
    match = re.search(r"(https?://[^\s]+)", text)
    return match.group(1) if match else ""

def normalize_url(url: str) -> str:
    if "youtu.be/" in url:
        video_id = url.split("/")[-1].split("?")[0]
        return f"https://www.youtube.com/watch?v={video_id}"
    return url

def get_youtube_direct_url(url: str) -> str:
    ydl_opts = {
        "quiet": True, 
        "skip_download": True, 
        "format": "mp4[height<=720]/best[ext=mp4]/best",
        "socket_timeout": 10
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
        return info.get("url")

def download_youtube_video(url: str, out_path: str) -> str:
    ydl_opts = {
        "outtmpl": os.path.join(out_path, "%(title).50s.%(ext)s"),
        "format": "best[height<=720][ext=mp4]/best[ext=mp4]",
        "noplaylist": True,
        "quiet": True,
        "retries": 1,
        "merge_output_format": "mp4",
        "concurrent_fragment_downloads": 4,
        "socket_timeout": 15,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        return ydl.prepare_filename(info)

def check_cookies_file():
    if not os.path.exists("cookies.txt"):
        logger.error("❌ Файл cookies.txt не найден!")
        return False
    logger.info("✅ Файл cookies.txt найден")
    return True

async def cleanup_user_message(message, delay: int = 2):
    try:
        await asyncio.sleep(delay)
        await message.delete()
        logger.info(f"🗑️ Удалено сообщение пользователя {message.from_user.id}")
    except Exception as e:
        logger.warning(f"Не удалось удалить сообщение: {e}")

def cleanup_old_processed_messages():
    global processed_messages
    if len(processed_messages) > 1000:
        processed_messages = set(list(processed_messages)[-500:])
        logger.info("🧹 Очищены старые записи из processed_messages")

def safe_remove_directory(dir_path: str):
    try:
        if os.path.exists(dir_path):
            shutil.rmtree(dir_path)
            logger.info(f"✅ Удалена директория: {dir_path}")
    except Exception as e:
        logger.warning(f"⚠️ Не удалось удалить директорию {dir_path}: {e}")

def validate_and_fix_extension(file_path: str) -> str:
    if not os.path.exists(file_path):
        return file_path
    
    try:
        import filetype
        kind = filetype.guess(file_path)
        
        if kind is None:
            return file_path
        
        current_ext = os.path.splitext(file_path)[1].lower()
        correct_ext = f".{kind.extension}"
        
        if current_ext != correct_ext:
            new_file_path = os.path.splitext(file_path)[0] + correct_ext
            try:
                os.rename(file_path, new_file_path)
                logger.info(f"✅ Исправлено расширение: {current_ext} -> {correct_ext}")
                return new_file_path
            except Exception as e:
                logger.warning(f"⚠️ Не удалось исправить расширение: {e}")
    except ImportError:
        logger.warning("⚠️ Библиотека filetype не установлена, пропускаем проверку расширений")
    
    return file_path

# ------------------------- ИНИЦИАЛИЗАЦИЯ ЗАГРУЗЧИКА -------------------------
instagram_downloader = InstagramDownloader()

# ------------------------- ОПТИМИЗИРОВАННЫЕ ОБРАБОТЧИКИ СООБЩЕНИЙ -------------------------

@app.on_message(filters.command("start"))
async def start(client, message):
    logger.info(f"📩 Получена команда /start от {message.from_user.id}")
    
    message_id = f"start_{message.id}_{message.from_user.id}"
    
    if message_id in processed_messages:
        logger.info("🔄 Пропускаем дублирующее сообщение /start")
        return
        
    processed_messages.add(message_id)
    
    try:
        welcome_msg = await message.reply_text(
            "⚡ **БЫСТРЫЙ Instagram Downloader** ⚡\n\n"
            "📥 Отправь ссылку на Instagram — я скачаю МГНОВЕННО:\n"
            "• 📹 Видео и рилсы\n"
            "• 📸 Фото\n"
            "• 🖼️ Карусели\n"
            "• 📱 Истории\n\n"
            "🚀 Оптимизировано для максимальной скорости!"
        )
        logger.info(f"✅ Отправлено приветственное сообщение пользователю {message.from_user.id}")
    except Exception as e:
        logger.error(f"❌ Ошибка отправки приветствия: {e}")
    
    cleanup_old_processed_messages()

@app.on_message(filters.command(["help", "info"]))
async def help_command(client, message):
    logger.info(f"📩 Получена команда help от {message.from_user.id}")
    
    message_id = f"help_{message.id}_{message.from_user.id}"
    
    if message_id in processed_messages:
        return
        
    processed_messages.add(message_id)
    
    help_text = (
        "🤖 **Помощь по боту**\n\n"
        "📥 Просто отправь ссылку на:\n"
        "• Instagram фото/видео/рилс\n"
        "• Instagram карусель\n" 
        "• Instagram историю\n\n"
        "⚡ **ОПТИМИЗИРОВАНО ДЛЯ СКОРОСТИ!**\n"
        "📌 Бот автоматически определит тип контента"
    )
    
    try:
        await message.reply_text(help_text)
        logger.info(f"✅ Отправлена помощь пользователю {message.from_user.id}")
    except Exception as e:
        logger.error(f"❌ Ошибка отправки помощи: {e}")
    
    cleanup_old_processed_messages()

@app.on_message(filters.text & filters.private)
async def handle_text(client, message):
    logger.info(f"📩 Получено сообщение от {message.from_user.id}: {message.text[:50]}...")
    
    message_id = f"text_{message.id}_{message.from_user.id}"
    
    if message_id in processed_messages:
        logger.info("🔄 Пропускаем дублирующее сообщение")
        return
        
    if message.text and message.text.startswith('/'):
        logger.info("⚙️ Пропускаем команду")
        return
    
    user_id = message.from_user.id
    text = message.text.strip()
    
    url = extract_first_url(text)
    logger.info(f"🔍 Извлечен URL: {url}")
    
    if not url or not any(d in url for d in ["youtube.com", "youtu.be", "instagram.com"]):
        logger.info("❌ URL не найден или не поддерживается")
        return

    processed_messages.add(message_id)
    
    if user_id in user_processing and user_processing[user_id]:
        logger.info(f"⏳ Пользователь {user_id} уже обрабатывается")
        try:
            await message.reply_text("⏳ Ваш предыдущий запрос еще обрабатывается...")
        except Exception as e:
            logger.warning(f"Не удалось отправить сообщение о занятости: {e}")
        return

    user_processing[user_id] = True
    processing_msg = None

    try:
        # Создаем временную директорию
        with tempfile.TemporaryDirectory() as temp_dir:
            logger.info(f"📁 Создана временная директория: {temp_dir}")
            
            processing_msg = await message.reply_text("⚡ Скачиваю контент...")
            
            # Определяем тип контента и скачиваем
            if "instagram.com" in url:
                logger.info("📸 Обнаружена Instagram ссылка")
                
                if not check_cookies_file():
                    await processing_msg.edit_text("⚠️ Файл cookies.txt не найден. Скачивание может не работать для приватного контента.")
                    await asyncio.sleep(2)
                
                result = await instagram_downloader.download_instagram_content(url, temp_dir)
                
            elif "youtube.com" in url or "youtu.be" in url:
                logger.info("🎥 Обнаружена YouTube ссылка")
                normalized_url = normalize_url(url)
                file_path = download_youtube_video(normalized_url, temp_dir)
                result = {
                    'type': 'video',
                    'files': [file_path],
                    'title': os.path.basename(file_path),
                    'webpage_url': normalized_url
                }
            else:
                await processing_msg.edit_text("❌ Неподдерживаемый тип ссылки")
                return

            if not result or not result.get('files'):
                await processing_msg.edit_text("❌ Не удалось скачать контент")
                return

            # Отправляем контент пользователю
            files = result['files']
            content_type = result.get('type', 'unknown')
            
            await processing_msg.edit_text(f"📤 Отправляю {len(files)} файл(ов)...")
            
            if content_type in ['photo', 'story_photo'] and len(files) == 1:
                # Одно фото
                file_path = validate_and_fix_extension(files[0])
                await message.reply_photo(
                    photo=file_path,
                    caption=f"📸 Instagram Photo\n🔗 {url}"
                )
                
            elif content_type in ['video', 'story_video'] and len(files) == 1:
                # Одно видео
                file_path = validate_and_fix_extension(files[0])
                await message.reply_video(
                    video=file_path,
                    caption=f"🎥 Instagram Video\n🔗 {url}",
                    supports_streaming=True
                )
                
            elif content_type == 'carousel' or len(files) > 1:
                # Карусель или несколько файлов
                media_group = []
                for i, file_path in enumerate(files):
                    file_path = validate_and_fix_extension(file_path)
                    if file_path.lower().endswith(('.jpg', '.jpeg', '.png')):
                        if i == 0:
                            media_group.append(InputMediaPhoto(file_path, caption=f"🖼️ Instagram Post\n🔗 {url}"))
                        else:
                            media_group.append(InputMediaPhoto(file_path))
                    elif file_path.lower().endswith(('.mp4', '.mov', '.avi')):
                        if i == 0:
                            media_group.append(InputMediaVideo(file_path, caption=f"🎥 Instagram Video\n🔗 {url}"))
                        else:
                            media_group.append(InputMediaVideo(file_path))
                
                if media_group:
                    await message.reply_media_group(media_group)
                    
            else:
                # Fallback - отправляем все файлы по отдельности
                for file_path in files:
                    file_path = validate_and_fix_extension(file_path)
                    if file_path.lower().endswith(('.jpg', '.jpeg', '.png')):
                        await message.reply_photo(file_path)
                    elif file_path.lower().endswith(('.mp4', '.mov', '.avi')):
                        await message.reply_video(file_path, supports_streaming=True)
                    else:
                        await message.reply_document(file_path)
            
            await processing_msg.edit_text("✅ Контент успешно отправлен!")
            logger.info(f"✅ Успешно обработан запрос от {user_id}")

    except Exception as e:
        logger.error(f"❌ Ошибка обработки запроса {user_id}: {e}")
        try:
            if processing_msg:
                await processing_msg.edit_text(f"❌ Ошибка при обработке: {str(e)}")
            else:
                await message.reply_text(f"❌ Ошибка при обработке: {str(e)}")
        except Exception as reply_error:
            logger.error(f"❌ Не удалось отправить сообщение об ошибке: {reply_error}")
    finally:
        user_processing[user_id] = False
        cleanup_old_processed_messages()
        
        # Очистка сообщений
        try:
            await cleanup_user_message(message)
            if processing_msg:
                await asyncio.sleep(5)
                await processing_msg.delete()
        except Exception as e:
            logger.warning(f"⚠️ Ошибка при очистке сообщений: {e}")

# ------------------------- ЗАПУСК БОТА -------------------------
if __name__ == "__main__":
    logger.info("🚀 Запуск Instagram Downloader Bot...")
    
    # Создаем необходимые директории
    os.makedirs("downloads", exist_ok=True)
    
    # Проверяем зависимости
    try:
        import filetype
        logger.info("✅ Библиотека filetype доступна")
    except ImportError:
        logger.warning("⚠️ Библиотека filetype не установлена - проверка расширений отключена")
    
    app.run()
    logger.info("👋 Бот остановлен")
